export { Page as Home } from './Home'
export {Page as Profile } from './Profile'
export { Page as Settings} from './Settings'
export { Page as Games} from './Games'
export { Page as Signup} from './CreateAccount'
export { Page as Login} from './LoginAccount'